# Generated by Django 3.1.3 on 2021-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_make',
            field=models.CharField(help_text='Format vehicle_name vehicle make', max_length=50, verbose_name='Vehicle Make'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_model',
            field=models.CharField(help_text='Format Vehicle model', max_length=50, verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_year',
            field=models.CharField(help_text='Format vehicle_name vehicle model year', max_length=50, verbose_name='Vehicle Year'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_make',
            field=models.CharField(help_text='Format vehicle_name vehicle make', max_length=50, verbose_name='Vehicle Make'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_model',
            field=models.CharField(help_text='Format Vehicle model', max_length=50, verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_year',
            field=models.CharField(help_text='Format vehicle_name vehicle model year', max_length=50, verbose_name='Vehicle Year'),
        ),
    ]
