# Generated by Django 3.1.3 on 2021-02-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0003_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_color',
            field=models.CharField(default='White', max_length=50, verbose_name='Vehicle Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorthirdpartypolicy',
            name='vehicle_color',
            field=models.CharField(default='White', max_length=50, verbose_name='Vehicle Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_make',
            field=models.CharField(max_length=50, verbose_name='Vehicle Make'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_model',
            field=models.CharField(max_length=50, verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_year',
            field=models.CharField(max_length=50, verbose_name='Vehicle Year'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_make',
            field=models.CharField(max_length=50, verbose_name='Vehicle Make'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_model',
            field=models.CharField(max_length=50, verbose_name='Vehicle Model'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_year',
            field=models.CharField(max_length=50, verbose_name='Vehicle Year'),
        ),
    ]
