# Generated by Django 3.1.3 on 2021-02-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0004_auto_20210209_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of Payment'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Policy', 'Policy'), ('Claims', 'Claims')], max_length=50, verbose_name='Type')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
