# Generated by Django 3.1.3 on 2021-02-10 17:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0005_auto_20210209_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationtoken',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushnotificationtoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Push Token'),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('data', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbl.pushnotificationtoken')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
