# Generated by Django 3.1.3 on 2021-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0006_auto_20210210_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotification',
            options={'verbose_name_plural': 'Notifications'},
        ),
    ]
