# Generated by Django 3.1.3 on 2021-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0008_pushnotification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read?'),
        ),
    ]
