# Generated by Django 3.1.3 on 2021-02-16 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0009_pushnotification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Added')),
            ],
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='data',
            field=models.TextField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Sent'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last Modified'),
        ),
    ]
