# Generated by Django 3.1.3 on 2021-02-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0010_auto_20210216_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcomprehensivepolicy',
            name='duration',
            field=models.CharField(choices=[('Half', 'Half'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Yearly', max_length=50, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorthirdpartypolicy',
            name='duration',
            field=models.CharField(choices=[('Half', 'Half'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Yearly', max_length=50, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('percentage', models.CharField(choices=[('QUARTERLY', '25'), ('HALF', '50'), ('YEARLY', '100')], default='100', max_length=50, verbose_name='Percentage')),
                ('start', models.DateTimeField(verbose_name='Start Date')),
                ('end', models.DateTimeField(verbose_name='End Date')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kbl.policy', verbose_name='Policy')),
            ],
        ),
    ]
