# Generated by Django 3.1.3 on 2021-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0011_auto_20210218_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcomprehensivepolicy',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='motorthirdpartypolicy',
            name='duration',
        ),
        migrations.AddField(
            model_name='policy',
            name='duration',
            field=models.CharField(choices=[('Half', 'Half'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Yearly', max_length=50, verbose_name='Duration'),
        ),
    ]
