# Generated by Django 3.1.3 on 2021-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0013_auto_20210218_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
    ]
