# Generated by Django 3.1.3 on 2021-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0015_auto_20210218_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-when']},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='proof_of_ownership',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pow', verbose_name='Proof of ownership'),
        ),
        migrations.AlterField(
            model_name='motorcomprehensivepolicy',
            name='vehicle_license',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='licenses', verbose_name='Vehicle License'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='proof_of_ownership',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pow', verbose_name='Proof of ownership'),
        ),
        migrations.AlterField(
            model_name='motorthirdpartypolicy',
            name='vehicle_license',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='licenses', verbose_name='Vehicle License'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Back image of property', max_length=255, null=True, upload_to='policy', verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front image of property', max_length=255, null=True, upload_to='policy', verbose_name='Front Image'),
        ),
    ]
