# Generated by Django 3.1.3 on 2021-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0016_auto_20210222_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='in_active_reason',
            field=models.CharField(blank=True, choices=[(1, 'In complete purchase'), (2, 'Under Review'), (3, 'Policy has expired')], max_length=255, null=True, verbose_name='Why In Active'),
        ),
    ]
