# Generated by Django 3.1.3 on 2021-03-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0019_auto_20210310_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-is_active', 'last_modified'], 'verbose_name_plural': 'All Policies'},
        ),
    ]
