# Generated by Django 3.1.3 on 2021-03-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0020_auto_20210310_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-is_active', '-last_modified'], 'verbose_name_plural': 'All Policies'},
        ),
    ]
