# Generated by Django 3.1.3 on 2021-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbl', '0021_auto_20210310_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referrer'),
        ),
    ]
