# Generated by Django 3.1.3 on 2021-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Individual Fullname (surname First), Corporate (Business name)', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone')),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Policy number')),
                ('occupation', models.CharField(blank=True, max_length=50, verbose_name='Occupation')),
                ('sector', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Co-operative', 'Co-operative'), ('Association', 'Association'), ('Construction', 'Construction'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Estate', 'Estate'), ('Financial Services', 'Financial Services'), ('Foreign Mission/Diplomat', 'Foreign Mission/Diplomat'), ('General Merchant', 'General Merchant'), ('Government', 'Government'), ('Hotels / Hospitality', 'Hotels / Hospitality'), ('Information Technology', 'Information Technology'), ('Insurance', 'Insurance'), ('Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Medical', 'Medical'), ('NGO', 'NGO'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Real Estates', 'Real Estates'), ('Religious Institutions', 'Religious Institutions'), ('Schools', 'Schools'), ('Ship Building / Maintenance', 'Ship Building / Maintenance'), ('SME', 'SME'), ('Supermarkets / Stores', 'Supermarkets / Stores'), ('Telecoms', 'Telecoms'), ('Transportation', 'Transportation')], help_text='Business Sector', max_length=50, null=True, verbose_name='Sector')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Abuja', ' Abuja'), ('Adamawa', ' Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', ' Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=50, verbose_name='State')),
                ('id_type', models.CharField(choices=[('National ID', 'National ID'), ('Drivers License', 'Drivers License'), ('Int Passport', 'Int Passport'), ('Voters card', 'Voters Card'), ('Certificate of Incorporation', 'Certificate of Incorporation')], max_length=50, verbose_name='Type of ID')),
                ('id_number', models.CharField(max_length=50, verbose_name='ID Number')),
                ('id_image', models.ImageField(help_text='Upload image of ID', upload_to='identification', verbose_name='Upload Image')),
                ('issued_at', models.DateField(verbose_name='Issued Date')),
                ('expired_at', models.DateField(verbose_name='Expiry Date')),
                ('is_corporate', models.BooleanField(help_text='Select if corporate', verbose_name='Corporate organization')),
                ('is_individual', models.BooleanField(help_text='Select if individual', verbose_name='Individual')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('website', models.URLField(blank=True, max_length=254, null=True, verbose_name='Website')),
                ('inc_cert', models.ImageField(blank=True, help_text='Upload image of certificate of incorporation', null=True, upload_to='certificate', verbose_name='Upload Image')),
                ('inc_date', models.DateField(blank=True, null=True, verbose_name='Incorporation Date')),
                ('tin', models.BigIntegerField(blank=True, null=True, verbose_name='Tax Identification Number')),
                ('rc_number', models.BigIntegerField(blank=True, null=True, verbose_name='Registration Number')),
                ('signature', models.ImageField(help_text='Upload image of Signature', upload_to='signature', verbose_name='Signature')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other Information')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Enrolled Date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
    ]
